# server {
#   listen  8080;
#   server_name localhost;
# 
#   return 301 https://$host$request_uri;
#   
#   # 1. 防止點擊劫持 (Clickjacking)
#   # add_header X-Frame-Options "SAMEORIGIN";
#   # 2. 防止 MIME 類型嗅探
#   # add_header X-Content-Type-Options "nosniff";
#   # 3. 隱藏 Nginx 版本號
#   # server_tokens off;
# 
#   # location / {
#   #   root   /opt/app-root/src;
#   #   index  index.html index.htm;
#   #   # 4. 針對 Flutter/React 的路由優化
#   #   try_files $uri $uri/ /index.html;
#   # }
# }

server {
  listen 8443 ssl;
  # server_name localhost;
  server_name _;

  ssl_certificate     /etc/nginx/certs/server.crt;
  ssl_certificate_key /etc/nginx/certs/server.key;

  # 現代安全性建議設定
  ssl_protocols        TLSv1.2 TLSv1.3;
  ssl_ciphers          HIGH:!aNULL:!MD5;

  location / {
      root   /opt/app-root/src;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
  }

}
