version: 3.8

networks:
  frontend:
    driver: bridge
    ipam:
      config: [{subnet: 10.101.1.0/24, gateway: 10.101.1.1}]
  vcl_backend_redis:
    driver: bridge
    ipam:
      config: [{subnet: 10.66.0.0/24, gateway: 10.66.0.1}]

services:
  vclredis:
    image: registry.redhat.io/rhel9/redis-7:latest
    container_name: vclredis
    environment: 
      - REDIS_PASSWORD=vclpasswd
    volumes:
      - ./redis_data:/var/lib/redis/data:Z
    networks:
      vcl_backend_redis: {ipv4_address: 10.66.0.3}

  pgsql_db:
    image: registry.redhat.io/rhel9/mariadb-1011
    container_name: mariadb_db
    ports:
      - "3306:3306"   # for development
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=services
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vision_db
    volumes:
      - ./sqldata/:/var/lib/pgsql/data:Z,U
    networks:
      vcl_backend_redis: {ipv4_address: 10.66.0.4}

