version: 3.8

networks:
  frontend:
    driver: bridge
    ipam:
      config: [{subnet: 10.101.1.0/24, gateway: 10.101.1.1}]
  backend_redis:
    driver: bridge
    ipam:
      config: [{subnet: 10.66.0.0/24, gateway: 10.66.0.1}]

services:
  vclredis:
    image: registry.redhat.io/rhel9/redis-7:latest
    container_name: vclredis
    environment: 
      - REDIS_PASSWORD=vclpasswd
    volumes:
      - ./redis_data:/var/lib/redis/data:Z
    networks:
      backend_redis: {ipv4_address: 10.66.0.3}

  mariadb_db:
    image: registry.redhat.io/rhel9/mariadb-1011
    container_name: mariadb_db
    ports:
      - "3306:3306"   # for development
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=services
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vision_db
    volumes:
      - ./sqldata/:/var/lib/mysql:Z,U
    networks:
      backend_redis: {ipv4_address: 10.66.0.4}

  core_pj:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/my-ubi-python:latest
    container_name: core_pj
    environment:
      - core_project=core_project
    networks:
      - frontend
      - backend_redis
    userns: keep-id
    volumes:
      - ./coreVcl:/app:Z #,U 最後到生產環境時還是需要加上
    command: tail -f /dev/null # ready for development

  vclnginx:
    image: registry.redhat.io/ubi8/nginx-122:latest
    container_name: vclnginx
    # 開發完之後需未來如果你把 core_pj 的 command 改回跑後端服務（如 Gunicorn），且需
    # 要 Nginx 精準等到後端「服務完全就緒（可連線狀態）」才開，那需要在 core_pj 裡加上
    # healthcheck 設定，並把 depends_on 改寫成 condition: service_healthy 模式。
    depends_on:
      - core_pj
    # 開啟可以在本地測試
    # ports:
    #   - "8080:8080"
    #   - "8443:8443"
    volumes:
      - ./server-vcl/nginx_conf/conf/nginx/standalone.conf:/etc/nginx/nginx.conf:Z
      - ./server-vcl/nginx_conf/conf/certs/:/etc/nginx/certs:Z,ro 
      # - ./coreVcl/templates/:/opt/app-root/src:Z,ro
      - ./coreVcl/static/:/opt/app-root/src/static:Z,ro
    networks:
      - frontend
    command: nginx -g "daemon off;"
  vcl_tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: vcl_tunnel
    depends_on:
      - vclnginx
    networks: 
      - frontend
    command:
      - tunnel
      - --protocol
      - http2
      - --url 
      - https://vclnginx:8443
      - --no-tls-verify



